name: taqam
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  intl: ^0.18.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  hexcolor: ^3.0.1
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.9
  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  curved_navigation_bar: ^1.0.3
  image_cropper: ^5.0.0
  chewie: ^1.3.5
  scrollable_positioned_list: ^0.3.5
  sliding_sheet: ^0.5.2
  syncfusion_flutter_calendar: ^20.3.48
  google_fonts: ^4.0.4
  date_picker_timeline: ^1.2.3
  animated_bottom_navigation_bar: ^1.1.0+1
  icon_broken: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_image_compress: ^2.0.4
  permission_handler: ^11.0.0
  flutter_sound: ^9.2.13
  audioplayers: ^5.1.0
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  soundpool: ^2.4.1
  flutter_notification_channel: ^2.0.0
  flutter_local_notifications: ^15.1.1
  get: ^4.6.5
  crypto: ^3.0.3
  timeago: ^3.5.0
  video_compress: ^3.1.2
  video_player: ^2.7.2
  read_more_text: ^0.0.5
  location: ^5.0.3
  geolocator: ^10.1.0
  url_launcher: ^6.1.14
  maps_launcher: ^2.2.0
  workmanager: ^0.5.2
  video_uploader: ^1.1.0
  geocoding: ^2.1.1
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^5.0.2
  eva_icons_flutter: ^3.1.0
  snapping_bottom_sheet: ^1.0.4
  camera_gallery_image_picker: ^0.0.4
  dropdown_button2: ^2.3.9
  flutter_colorpicker: ^1.0.3
  #/* Firebase packages
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^2.24.2
  # Flutter plugin for Firebase Auth, enabling authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter.
  firebase_auth: ^4.9.0
  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization and offline support on Android and iOS.
  cloud_firestore: ^4.14.0
  # Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS.
  firebase_storage: ^11.2.6
  # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  firebase_messaging: ^14.6.7
  # An easy-to-use firebase phone authentication package to easily send and verify OTP's with auto-fetch OTP support via SMS. Supports web out of the box.
  firebase_phone_auth_handler: ^1.0.8
  # App Check works alongside other Firebase services to help protect your backend resources from abuse, such as billing fraud or phishing.
  firebase_app_check: ^0.2.1+8
  # Flutter plugin for Google Sign-In, a secure authentication system for signing in with a Google account.
  google_sign_in: ^6.1.6
  #*/
  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.3.5
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models.
  flutter_screenutil: ^5.9.0
  # Flutter package to show beautiful dialogs.
  awesome_dialog: ^3.2.0
  # Show UI elements according for conditional type and supports null safety
  conditional_builder_null_safety: ^0.0.6
  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.2
  # For calling RestAPIs
  http: ^1.0.0
  # For showing Emojis
  emoji_picker_flutter: ^1.0.0
  # For storing images into gallery
  gallery_saver: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_floating_bottom_bar: ^1.2.0
  # Get a name for given Color. This package contains hardcoded names for 2231 color values. For an input color, it finds a name in the list which has the closest match.
  colornames: ^0.1.0



dependency_overrides:
  http: ^0.13.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ta2m_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
